### ISSUE TITLE
Can't access products from admin

### ISSUE THREAD

**Issue by sorokinvj** [cezerin/cezerin#405]
2018-03-19T10:35:35.064+0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:60366 #4 (4 connections now open)
error: API error MongoError: The top-level _id field is the only field currently supported for exclusion
    at queryCallback (/Users/vladislavsorokin/Yandex.Disk.localized/Documents/webprojects/cezerin/node_modules/mongodb-core/lib/cursor.js:223:25) at /Users/vladislavsorokin/Yandex.Disk.localized/Documents/webprojects/cezerin/node_modules/mongodb-core/lib/connection/pool.js:541:18 at process._tickCallback (internal/process/next_tick.js:112:11)

I added default db data from your tutorial already

**Comment by ersah123** [comment]
#401

**Comment by sorokinvj** [comment]
upgrading to mongodb 3.6 was a real pain (mac os sierra), but it helped

**Comment by sonufrienko** [comment]
@sorokinvj 
I use Docket to run MongoDB. It takes 1 min to run/change any version.
Docker in development is time saver :+1:
