### ISSUE TITLE
TypeError: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by faladinojames** [cezerin/cezerin#459]
After setting up the project for this first time, I get this error every time I load  a page.
` Page error / TypeError: Cannot read property 'pathname' of undefined
    at createPath (E:\Projects\cezerin\node_modules\history\PathUtils.js:49:27)
    at createURL (E:\Projects\cezerin\node_modules\react-router\StaticRouter.js:80:78)
    at Object.StaticRouter._this.createHref (E:\Projects\cezerin\node_modules\react-router\StaticRouter.js:111:69)
    at Link.render (E:\Projects\cezerin\node_modules\react-router-dom\Link.js:83:44)
    at resolve (E:\Projects\cezerin\node_modules\react-dom\cjs\react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (E:\Projects\cezerin\node_modules\react-dom\cjs\react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (E:\Projects\cezerin\node_modules\react-dom\cjs\react-dom-server.node.development.js:2234:19)
    at renderToString (E:\Projects\cezerin\node_modules\react-dom\cjs\react-dom-server.node.development.js:2501:25)
    at getAppHtml (E:\Projects\cezerin\dist\store\server\pageRendering.js:83:41)
    at renderPage (E:\Projects\cezerin\dist\store\server\pageRendering.js:131:17)
`

**Comment by camelotceo** [comment]
any luck?

**Comment by faladinojames** [comment]
Upgrading to Mongo 3.6 fixes the problem
