### ISSUE TITLE
Useless message when an exception occurs on the project start

### ISSUE THREAD

**Issue by sonufrienko** [cezerin/cezerin#522]
I got a useless message when an exception occurs on the project start (`npm start`).

### console

[api] npm ERR! code ELIFECYCLE
[api] npm ERR! errno 1
[api] npm ERR! cezerin@0.33.0 start-api: `node -r esm src/api/server/index.js`
[api] npm ERR! Exit status 1
[api] npm ERR! 
[api] npm ERR! Failed at the cezerin@0.33.0 start-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[api] 

### NPM Logs

13 verbose stack Error: cezerin@0.33.0 start-api: `node -r esm src/api/server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by sonufrienko** [comment]
Now, we'll see stack on any exception.
